{% set version = "0.9.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dofuture
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/doFuture_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/doFuture/doFuture_{{ version }}.tar.gz
  sha256: 294c6823de241f8a3fc9745ae5c93e54bddea916ccf79608cf3dc02b1facdee9

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-foreach >=1.4.4
    - r-future >=1.14.0
    - r-globals >=0.12.4
    - r-iterators >=1.0.9
  run:
    - r-base
    - r-foreach >=1.4.4
    - r-future >=1.14.0
    - r-globals >=0.12.4
    - r-iterators >=1.0.9

test:
  commands:
    - $R -e "library('doFuture')"           # [not win]
    - "\"%R%\" -e \"library('doFuture')\""  # [win]

about:
  home: https://github.com/HenrikBengtsson/doFuture
  license: LGPL-2.1
  summary: Provides a '%dopar%' adapter such that any type of futures can be used as backends
    for the 'foreach' framework.
  license_family: LGPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2.1'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: doFuture
# Version: 0.8.2
# Title: A Universal Foreach Parallel Adapter using the Future API of the 'future' Package
# Depends: globals (>= 0.12.4), future (>= 1.14.0), foreach (>= 1.4.4), iterators (>= 1.0.9), parallel, utils
# Suggests: doRNG (>= 1.6.6), markdown, R.rsp
# VignetteBuilder: R.rsp
# Authors@R: c(person("Henrik", "Bengtsson", role=c("aut", "cre", "cph"), email = "henrikb@braju.com"))
# Description: Provides a '%dopar%' adapter such that any type of futures can be used as backends for the 'foreach' framework.
# License: LGPL (>= 2.1)
# LazyLoad: TRUE
# URL: https://github.com/HenrikBengtsson/doFuture
# BugReports: https://github.com/HenrikBengtsson/doFuture/issues
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-10-30 01:22:11 UTC; hb
# Author: Henrik Bengtsson [aut, cre, cph]
# Maintainer: Henrik Bengtsson <henrikb@braju.com>
# Repository: CRAN
# Date/Publication: 2019-10-30 07:10:03 UTC
