travis:
  secure:
    BINSTAR_TOKEN: f3eqY/zBFkxcM+08/IiYLRxeCTGMq/68YHt898VfunVFyGj/99S4ChjUIpHPqGcD4tHsvVebGvtfj0LHM+4+JRc2lDDRB/NdSV1L5Ghqa2ZWvx66T9tElF/y3F6ezRLzsIjJ1XHpsgCs0QkvYllCASQ8X+O33aIi86pXVp7jtbwhSG9uO8Soq4QSVJKdicStui34iZYoFp5yztp+gOi8tYOS/HJy3zc6jDsUYzo/UnwPqYjWWpzaV/Vx9aVJHxskCuszWnWQO8zfKr2Fu51yc/+jHh4606NWSt3HKxIeCw8+1jmt2UEgDvJwGmBP4IE4gQHN1s/jDZ6up42OV/6V/5kUmRrftZJW2YKqzYDiD2y54Vddqy9RlgEWpRya3PV+t6R5/kN8v38ea37+6x38ub7YUT91slcczxzlskdlDc52P/l6pw3ExiXPgqZpMlH+1jvaqJdyxaEJ3YniXcDEuvx44e6lqk81DdkzD/88h/XCwPF9Lw1MrIE49EDgfwXCxfxUEc70bagduAQlxPBpEnY916CKFzN214m0gBub/+XQ+r9Jc9XIK2eJ5+UBu8v4sDq3JlFfZIusluPyMeMarerSsEECNqZns+YkO85O2ac3XurGvk2Foi74XbgapBxWOQqI3B/fKR68j7Lb3F/HS6ndJJzhzDHrKHst1g6NccI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
