appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: OJ/JxiXNPknrKNtH4XD0zNgzeYnHO6+3BS7zLze/M1WdytWZz3i3Ze0RcvYsWn+b5xCe7ZM7bUhdPxBI+9Qyc2qagCalqAh9VZAMQn23B3AyXEk8hANXpS5EWRCJ/tMey2wqc5iMyitLbQg33gh6I0YWT5CM+l/hnrd1nrM4GKiItpywGsmnD4qo7g3MgusAK37Cly9REXszwHGQDVTOo32dJyLoncg3tit7toclEqneMznUHpBqpctmUUumNYCAvLHCoWuKwwKuxeoX/pcxVK3kLUDUkl8VkolDYAnnsWmZDXGV67vaTSKvmFnq7DQVfNpTmSEd8/BNZr04NfbcYAxYcC6pZNmWIwoEFYk99W+LBJsLacJjdeUDvCeULMLAmX1A4lfc8sq3cj/LtTJT4BAGknLcMVjkQRAxyMEuNxJe6bK9M1OumIXtuMiR0FJQ16jIqdpFtepDnOImHcbzRQOldUiF32WgtgPMjVqLa5AgkkUyGf6F1tGJL4kCqtusM1DZAPtLYCxCJmkrhddNS1bzRfOHHmZdysjV3a64EVIq/l/1AIYTOrc2GGWJwdA24bkUMXnfJ5v9WZCT/UvPmKuNqvz4/JQlXJ6srb8yw2Hgb62uwezjsHE7p8nlB9pNvSekYJAfH8Y+67frxWFZljhHuvJQc0Tb1nnJAHlhH+k=}
